# This file is used by Copier to track the template version
# and enable template updates in generated projects

_commit: f4f1d235602eafd3c611bd4fa8c1efe427acde5c
_src_path: gh:stateful-y/python-package-copier
author_email: gtauzin@stateful-y.io
author_name: Guillaume Tauzin
description: An Optuna integration for hyperparameter tuning in Yohou
github_username: stateful-y
include_actions: True
include_examples: True
license: Apache-2.0
max_python_version: '3.14'
min_python_version: '3.11'
package_name: yohou_optuna
project_name: Yohou-Optuna
project_slug: yohou-optuna
