# This file is used by Copier to track the template version
# and enable template updates in generated projects

_commit: c1343c6c8cf8ac01e92a81e7565e26590319af02
_src_path: gh:stateful-y/python-package-copier
author_email: gtauzin@stateful-y.io
author_name: Guillaume Tauzin
code_owner: '@gtauzin'
description: An Optuna integration for hyperparameter tuning in Yohou
github_username: stateful-y
include_actions: True
include_codecov: True
include_examples: True
license: Apache-2.0
max_python_version: '3.14'
min_python_version: '3.11'
package_name: yohou_optuna
project_name: Yohou-Optuna
project_slug: yohou-optuna
renovate_preset: 'stateful-y/renovate-config'
repo_visibility: public
