# Read the Docs configuration
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_create_environment:
      # Install uv via asdf (or system package) before creating the venv
      - asdf plugin add uv || true
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      # Create the virtual environment using uv
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      # Sync doc-dependencies (the group "docs") and install the project itself
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --group docs

# MkDocs configuration
mkdocs:
  configuration: mkdocs.yml
