name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen
      placeholder: |
        When I... I expected... but instead...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      placeholder: |
        ```python
        # Minimal code example
        ```
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        OS: Ubuntu 22.04
        Python: 3.11.5
        Version: 0.1.0
      value: |
        OS:
        Python:
        Version:
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Logs, stack traces, or anything else that might help
